name: RSS to Discord Auto Post

on:
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 8:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rss-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # We need to fetch all history for git pull to work correctly
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run bot, commit, and push in a loop
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_URL: ${{ secrets.RSS_URL }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # 1. Determine random post count
          DAY=$(date +%u)
          if [ "$DAY" -ge 6 ]; then
            MIN=5
            MAX=8
          else
            MIN=1
            MAX=4
          fi
          COUNT=$(( RANDOM % (MAX - MIN + 1) + MIN ))
          echo "Will post and commit $COUNT times today."

          # 2. Configure Git User
          git config --global user.email "ricky.zakariap@gmail.com"
          git config --global user.name "rickyzakariap"
          git remote set-url origin https://$GH_PAT@github.com/rickyzakariap/bot-push.git

          # 3. Loop for posting and committing
          for i in $(seq 1 $COUNT); do
            echo "--- Run #$i of $COUNT ---"
            node rss-to-discord.js
            
            # Check if there are any file changes
            if ! git diff-index --quiet HEAD; then
              echo "Changes detected. Committing and pushing..."
              git add -A
              git commit -m "Auto-post #${i} of ${COUNT}" || true # <-- TAMBAHKAN '|| true' DI SINI
              git pull origin main --rebase
              git push
            else
              echo "No file changes detected, skipping commit."
            fi
            
            sleep 10 # Wait 10 seconds between runs
          done
