name: RSS to Discord Auto Post

on:
  schedule:
    - cron: '0 7 * * *'   # Runs every 7 AM
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rss-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run RSS to Discord script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: node rss-to-discord.js

      - name: Show log.txt content
        run: cat log.txt

      - name: Show git status
        run: git status

      - name: Show git diff
        run: git diff

      - name: Commit log updates
        run: |
          git config --global user.email "ricky.zakariap@gmail.com"
          git config --global user.name "rickyzakariap"
          git add -A
          git commit -m "auto-update log.txt (numbered)" || echo "No changes to commit"

      - name: Pull latest changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$GH_PAT@github.com/rickyzakariap/bot-push.git
          git pull origin main --rebase

      - name: Push log updates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$GH_PAT@github.com/rickyzakariap/bot-push.git
          git push 
