name: RSS to Discord Auto Post

on:
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 8:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rss-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Determine post count and run bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: |
          DAY=$(date +%u)
          if [ "$DAY" -ge 6 ]; then
            # Weekend: Saturday (6) or Sunday (7)
            MIN=5
            MAX=8
          else
            # Weekday: Monday (1) to Friday (5)
            MIN=1
            MAX=4
          fi
          COUNT=$(( RANDOM % (MAX - MIN + 1) + MIN ))
          echo "Posting $COUNT times today"
          for i in $(seq 1 $COUNT); do
            echo "Run #$i"
            node rss-to-discord.js
            sleep 10 # Optional: wait 10 seconds between runs
          done

      - name: Show log.txt content
        run: cat log.txt

      - name: Show git status
        run: git status

      - name: Show git diff
        run: git diff

      - name: Commit log updates
        run: |
          git config --global user.email "ricky.zakariap@gmail.com"
          git config --global user.name "rickyzakariap"
          git add -A
          git commit -m "auto-update log.txt (numbered)" || echo "No changes to commit"

      - name: Pull latest changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$GH_PAT@github.com/rickyzakariap/bot-push.git
          git pull origin main --rebase

      - name: Push log updates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$GH_PAT@github.com/rickyzakariap/bot-push.git
          git push 
