name: RSS to Discord Auto Post

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rss-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run RSS to Discord script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: node rss-to-discord.js

      - name: Show log.txt content
        run: cat log.txt

      - name: Show git status
        run: git status

      - name: Show git diff
        run: git diff

      - name: Commit and push log updates
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add log.txt log_number.txt
          git commit -m "auto-update log.txt (numbered)" || echo "No changes to commit"
          git push 
